name: _

environment:
  sdk: '>=3.12.0 <3.13.0'
  flutter: '>=3.44.0 <3.45.0'

scripts:
  upgrade-dependencies: rps _upgrade-dependencies --directory=core &&
    rps _upgrade-dependencies --directory=backoffice &&
    rps _upgrade-dependencies --directory=app_wook &&
    rps _upgrade-dependencies --directory=app_button

  _upgrade-dependencies: dart pub upgrade --unlock-transitive --major-versions --tighten

workspace:
  - core
  - backoffice
  - app_wook
  - app_button
