# cast_nullable_to_non_nullable
global_options:
  source_gen:combining_builder:
    options:
      ignore_for_file:
        - cast_nullable_to_non_nullable
        - unnecessary_null_checks
        - unused_field

targets:
  $default:
    sources:
      exclude:
        - 'test/**'
    builders:
      source_gen:combining_builder:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
          - '**/*_model.dart'
          - '**/*routes.dart'

      mek_data_class_generator:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
          - '**/*_model.dart'
        options:
          changes_visible: false
          fields_class_visible: false

      json_serializable:json_serializable:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
        options:
          explicit_to_json: true
          create_factory: false
          create_to_json: false
