targets:
  $default:
    sources:
      exclude:
        - 'test/**'
    builders:
      source_gen:combining_builder:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
          - '**/*_model.dart'
          - '**/*routes.dart'
        options:
          ignore_for_file:
            - unused_field

      mek_data_class_generator:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
          - '**/*_model.dart'
        options:
          changes_visible: false
          fields_class_visible: false

      json_serializable:json_serializable:
        generate_for:
          - '**/*_dto.dart'
          - '**/*_dvo.dart'
        options:
          explicit_to_json: true

      go_router_builder:
        generate_for:
          - '**/*routes.dart'
